function paths = tmfc_save_nii_ROIs(outputdir,nROI)

% ========= Task-Modulated Functional Connectivity (TMFC) toolbox =========
% 
% Creates ROI masks for NIfTI time-series images generated by tmfc_save_nii.
% Each ROI mask consists of one voxel corresponding to one time series.
%
% WARNING: Please note that nROI should be equal to the number of ROIs in 
% NIfTI time-series images generated by tmfc_save_nii. It is necessary to 
% create new ROI masks every time you generate NIfTI time-series images
% with a different number of ROIs.
%
% paths = tmfc_save_nii_ROIs(outputdir,nROI)
%
% INPUTS:
% outputdir     - Path to save ROI masks
% nROI          - Number of ROIs
%
% OUTPUTS:
% paths - Full paths to ROI masks.
%
% =========================================================================
% Copyright (C) 2025 Ruslan Masharipov
% License: GPL-3.0-or-later
% Contact: masharipov@ihb.spb.ru

mask = eye(nROI);

if ~isdir(outputdir)
    mkdir(outputdir);
end

for iROI = 1:nROI
    nii_image = [];
    nii_image = make_nii(mask(:,iROI),[],[],2);
    paths(iROI).mask = fullfile(outputdir,['ROI_' num2str(iROI,'%05.f') '.nii']);
    save_nii(nii_image,paths(iROI).mask); 
end
end