function paths = tmfc_save_nii_ROIs(outputdir,nROI)

% ========= Task-Modulated Functional Connectivity (TMFC) toolbox =========
% 
% Creates ROI masks for NIfTI time-series images generated by tmfc_save_nii.
% Each ROI mask consists of one voxel corresponding to one time-series.
%
% WARNING: Please note that nROI should be equal to the number of ROIs in 
% NIfTI time-series images generated by tmfc_save_nii. It is necessary to 
% create new ROI masks every time you generate NIfTI time-series images
% with different numbers of ROIs.
%
% paths = tmfc_save_nii_ROIs(outputdir,nROI)
%
% INPUTS:
% output_dir    - Path to save ROI masks
% nROI          - Number of ROIs
%
% OUTPUTS:
% paths - Full paths to ROI masks.
%
% =========================================================================
%
% Copyright (C) 2025 Ruslan Masharipov
% 
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
% 
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with this program. If not, see <https://www.gnu.org/licenses/>.
%
% Contact email: masharipov@ihb.spb.ru

mask = eye(nROI);

if ~isdir(outputdir)
    mkdir(outputdir);
end

for iROI = 1:nROI
    nii_image = [];
    nii_image = make_nii(mask(:,iROI),[],[],2);
    paths(iROI).mask = fullfile(outputdir,['ROI_' num2str(iROI,'%05.f') '.nii']);
    save_nii(nii_image,paths(iROI).mask); 
end
end